stages:
  - build

build_job:
  stage: build
  tags:
    - DSTV3.Uploadinterface.Api
  script:
    - 'dotnet restore'
    - 'dotnet build --configuration Release'
    - 'dotnet publish --configuration Release --output /home/DSTV3.UploadInterface.Api_pub/'
  only:
    - master